
server:
  port: 8089

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://USER-SERVICE   # or lb://user-service with discovery
              predicates:
                - Path=/api/v1/users/**, /api/v1/auth/**
              filters:
                - StripPrefix=1
                - name: CircuitBreaker
                  args:
                    name: userService
                    fallbackUri: forward:/fallback/user
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 200
                    key-resolver: "#{@userKeyResolver}"

            - id: activity-service
              uri: lb://ACTIVITY-SERVICE   # or lb://activity-service with discovery
              predicates:
                - Path=/api/v1/activity/**
              filters:
                - StripPrefix=1
                - name: CircuitBreaker
                  args:
                    name: userService
                    fallbackUri: forward:/fallback/activity
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 200
                    key-resolver: "#{@userKeyResolver}"

          # Global CORS
          globalcors:
            corsConfigurations:
              '[/**]':
                allowedOrigins: "*"
                allowedMethods: "*"
                allowedHeaders: "*"
                allowCredentials: false
  data:
    redis:
      host: localhost
      port: 6379

#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://auth-service:8082/realms/your-realm  # Keycloak or your auth server

jwt:
  secret:
    key: "my-super-secret-key-my-super-secret-secret"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,prometheus
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      userService:
        slidingWindowSize: 100
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 10
